---
title: "Writing_assign_3"
author: "Jack Anthony 25067142"
date: "April 25, 2018"
output: html_document
---

The definition of “species” used in macroscopic biology is useless when applied to prokaryotes, as the definition relies on sexual reproduction producing viable offspring to determine whether two organisms belong to the same species. Currently, there is no clear definition of what a species is for prokaryotic organisms, due to a plethora of compounding reasons. Morphological differences present in prokaryotes are not as diverse as the global pool of microbial organisms, and the marker genes used in genetic definitions do not always retain their sequence across a whole species. On the other hand, there may not be enough differentiation in marker sequence even at the genus level to usefully separate organisms into appropriate species. Horizontal gene transfer (HGT) complicates the issue even further, as copies of DNA segments can spread across species and even genera, throwing a wrench into the workings of any species definition based on whole genome similarity. HGT frustrates the species definition aspect of microbiology, but it plays an important role in the maintenance of biogeochemical cycles. Environmental conditions may change such that a particular species will die out, but a horizontally transferred gene and its environmental function can persist in another species that is perhaps better suited to this new environment. Perhaps it is not even necessary to have a clear definition of prokaryotic species, outside of medical microbiology, because specific functions are what are important to humans. The net function of a microbial community matters more than which specific constituents make up the community. Tracking the evolution and diversity of genes over time may be more useful for environmental applications than species as it allows for a direct observation of function.

Traditionally, multicellular organisms were classified into the same species if their offspring were fertile. For microbes, who reproduce asexually by dividing one organism into two new ones, this definition completely misses the mark. Any attempt to classify prokaryotes by morphological features is also futile, as the range of diagnostic physical characteristics in unicellular organisms is just too small. Instead, modern microbiology relies on genetic similarities to classify organisms into species. Unfortunately, this genetic system is also fraught with problems. Different methods of determining genetic similarity are used by different researchers, including hybridization temperature, average nucleotide similarity across a genome, sequence similarity in a gene conserved across taxa, and sequence similarity in just one region of a gene ([Kim _et al._, 2014](https://www.ncbi.nlm.nih.gov/pubmed/24505072)). Since all of these definitions rely on some threshold value of similarity to determine whether a given sequence falls into one or another species, these arbitrarily-chosen threshold values provide another point of variation in how species are defined by different researchers. There is a fundamental tradeoff between taxonomic resolution and inclusion of organisms that would not normally be considered part of a certain species, when these thresholds are changed. Sequencing error and chimera generation can provide a source of false species to all genetic species definitions, limiting their utility as a system for determining diversity ([Kunin _et al._, 2010](https://www.ncbi.nlm.nih.gov/pubmed/19725865)).

A final source of trouble when determining a single, clean definition of a microbial species is HGT. When segments of DNA are exchanged between cells, relatively large chunks of sequence can be integrated into a new cell’s genome. Most researchers would say that an organism should still belong to the same species if all that has changed is the acquisition of a handful of additional genes among thousands of others. However, the functional capabilities of an organism can change dramatically, depending on which genes are incorporated ([Martinez _et al._, 2007](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1838496/)). Even commonly used taxonomic marker genes such as the 16S rRNA gene may be transferred horizontally ([Wooley _et al._, 2010](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000667)). One possibility of a species definition that could account for HGT would be using a metric of how many genes are shared between individuals. However, this option does not solve the issue of defining separation thresholds, but rather pushes it to the gene level instead of the organism level. 

Genes can persist within an environment on much longer timescales than prokaryotic species. When environmental conditions change, selective forces acting on microbial communities will also change and some species will die off or be reduced to extremely low abundance. The process of HGT allows organisms that are suited to life under the new environmental conditions to inherit biogeochemically important genes from dying species and expand to fill the newly absented niche. Even though species have been in a constant cycle of creation through mutation and removal by selection for over 4 billion years, the same core set of redox metabolic genes has been retained for nearly the full length of this period ([Falkowski _et al._, 2008](https://www.ncbi.nlm.nih.gov/pubmed/18497287)). HGT allows genes to evolve and function as autonomous entities, rather than components of an organism whose success is constrained by the overall organism's fitness. 

Medical microbiology has a longer history of species definition than environmental microbiology, and most established species in this field are defined via assayable chemical functions or physical characteristics. Function is still the attribute that is most important and pathogenicity islands can be transferred horizontally to new species that may not be identified by tests designed for the species originally carrying the genes. Exact definitions of whether an organism falls into one species or another are not medically important, only whether or not the organism causes illness. Historically, diversity has not been an important factor in medical microbiology, although the gut microbiome now bridges the fields of environmental and medical microbiology. A rock-solid species definition is not important if diversity does not matter. Because diagnosis is often time sensitive, genetic species definitions will not be useful in medical applications until sequencing and sequence data analysis can give results in the same amount of time as test strips designed to identify a certain species. In environmental microbiology, results are not quite as time sensitive and diversity of function and how it fluctuates spatiotemporally are important factors, so some unit of unique life needs to be defined.

Perhaps a clear species definition is not necessary if genes provide more pragmatic measurements of diversity, distribution, and potential function. Rather than arbitrary sequence identity thresholds to determine binning into what counts as a different gene, the definition could be primarily focussed on enzymatic function, with sequence similarity considered using a large threshold value as only a broad preliminary filter. Portions of enzymatic pathways are often lost to single genomes due to genome streamlining ([Giovannoni, 2017](https://www.ncbi.nlm.nih.gov/pubmed/27687974)), but the function of the whole pathway will be retained, as genes lost to a single organism will be distributed across the community ([Morris _et al._, 2012](http://mbio.asm.org/content/3/2/e00036-12.abstract)). Combined with the distribution of similar and identical genes through HGT, gene diversity and distribution within a community provide a much more comprehensive view of environmental function than species observations. 

Prokaryotes do not fit the multicellular system for species identification and no alternative has been universally agreed upon. Morphological features are insufficiently diverse, unless only a small pool of possible organisms is considered for identification, as with medical microbiology. Genetic systems of classification require a standardized portion of the genome to be observed, a standardized method of similarity measurement, and a standardized threshold for where the division between species lies. Sequencing error and horizontal gene transfer further complicate genetic species definitions as genome sequence does not follow a single path of phylogenetic inheritance to a last common ancestor. HGT provides a process that allows environmentally important genes to persist on a much longer timescale than the survival of a single species. This transfer of important genes highlights the significance of functions of specific genes and the disconnect between function and any definition of species. Defining genes as the smallest unit of life provides increased taxonomic resolution while maintaining a direct relationship to observed biogeochemical functions.